//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEASTAPI.Endpoint.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BEASTAPI.Endpoint.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address id: {0}..
        /// </summary>
        public static string Address_InvalidId {
            get {
                return ResourceManager.GetString("Address_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address page number: {0}..
        /// </summary>
        public static string Address_InvalidPageNumber {
            get {
                return ResourceManager.GetString("Address_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Id mismatch..
        /// </summary>
        public static string Address_Mismatch {
            get {
                return ResourceManager.GetString("Address_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No addreess found with id: {0}..
        /// </summary>
        public static string Address_NotFoundId {
            get {
                return ResourceManager.GetString("Address_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No address found..
        /// </summary>
        public static string Address_NotFoundList {
            get {
                return ResourceManager.GetString("Address_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is null..
        /// </summary>
        public static string Address_Null {
            get {
                return ResourceManager.GetString("Address_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid application log id: {0}..
        /// </summary>
        public static string ApplicationLog_InvalidId {
            get {
                return ResourceManager.GetString("ApplicationLog_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid application log id: {0}..
        /// </summary>
        public static string ApplicationLog_InvalidId1 {
            get {
                return ResourceManager.GetString("ApplicationLog_InvalidId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid application log page number: {0}..
        /// </summary>
        public static string ApplicationLog_InvalidPageNumber {
            get {
                return ResourceManager.GetString("ApplicationLog_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid application log page number: {0}..
        /// </summary>
        public static string ApplicationLog_InvalidPageNumber1 {
            get {
                return ResourceManager.GetString("ApplicationLog_InvalidPageNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application log found with id: {0}..
        /// </summary>
        public static string ApplicationLog_NotFoundId {
            get {
                return ResourceManager.GetString("ApplicationLog_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application log found with id: {0}..
        /// </summary>
        public static string ApplicationLog_NotFoundId1 {
            get {
                return ResourceManager.GetString("ApplicationLog_NotFoundId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application logs found..
        /// </summary>
        public static string ApplicationLog_NotFoundList {
            get {
                return ResourceManager.GetString("ApplicationLog_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application logs found..
        /// </summary>
        public static string ApplicationLog_NotFoundList1 {
            get {
                return ResourceManager.GetString("ApplicationLog_NotFoundList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application log is null..
        /// </summary>
        public static string ApplicationLog_Null {
            get {
                return ResourceManager.GetString("ApplicationLog_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application log is null..
        /// </summary>
        public static string ApplicationLog_Null1 {
            get {
                return ResourceManager.GetString("ApplicationLog_Null1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audit log id: {0}..
        /// </summary>
        public static string AuditLog_InvalidId {
            get {
                return ResourceManager.GetString("AuditLog_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audit log id: {0}..
        /// </summary>
        public static string AuditLog_InvalidId1 {
            get {
                return ResourceManager.GetString("AuditLog_InvalidId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audit log page number: {0}..
        /// </summary>
        public static string AuditLog_InvalidPageNumber {
            get {
                return ResourceManager.GetString("AuditLog_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audit log page number: {0}..
        /// </summary>
        public static string AuditLog_InvalidPageNumber1 {
            get {
                return ResourceManager.GetString("AuditLog_InvalidPageNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audit log found with id: {0}..
        /// </summary>
        public static string AuditLog_NotFoundId {
            get {
                return ResourceManager.GetString("AuditLog_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audit log found with id: {0}..
        /// </summary>
        public static string AuditLog_NotFoundId1 {
            get {
                return ResourceManager.GetString("AuditLog_NotFoundId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audit logs found..
        /// </summary>
        public static string AuditLog_NotFoundList {
            get {
                return ResourceManager.GetString("AuditLog_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audit logs found..
        /// </summary>
        public static string AuditLog_NotFoundList1 {
            get {
                return ResourceManager.GetString("AuditLog_NotFoundList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit log is null..
        /// </summary>
        public static string AuditLog_Null {
            get {
                return ResourceManager.GetString("AuditLog_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit log is null..
        /// </summary>
        public static string AuditLog_Null1 {
            get {
                return ResourceManager.GetString("AuditLog_Null1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token expired..
        /// </summary>
        public static string Auth_ExpiredRefreshToken {
            get {
                return ResourceManager.GetString("Auth_ExpiredRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token..
        /// </summary>
        public static string Auth_InvalidRefreshToken {
            get {
                return ResourceManager.GetString("Auth_InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login information is null..
        /// </summary>
        public static string Auth_LoginNull {
            get {
                return ResourceManager.GetString("Auth_LoginNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login information is null..
        /// </summary>
        public static string Auth_LoginNull1 {
            get {
                return ResourceManager.GetString("Auth_LoginNull1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information is null..
        /// </summary>
        public static string Auth_UserInfoNull {
            get {
                return ResourceManager.GetString("Auth_UserInfoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information is null..
        /// </summary>
        public static string Auth_UserInfoNull1 {
            get {
                return ResourceManager.GetString("Auth_UserInfoNull1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category &apos;{0}&apos; already exists..
        /// </summary>
        public static string Category_Duplicate {
            get {
                return ResourceManager.GetString("Category_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category &apos;{0}&apos; already exists..
        /// </summary>
        public static string Category_Duplicate1 {
            get {
                return ResourceManager.GetString("Category_Duplicate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category id: {0}..
        /// </summary>
        public static string Category_InvalidId {
            get {
                return ResourceManager.GetString("Category_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category id: {0}..
        /// </summary>
        public static string Category_InvalidId1 {
            get {
                return ResourceManager.GetString("Category_InvalidId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category page number: {0}..
        /// </summary>
        public static string Category_InvalidPageNumber {
            get {
                return ResourceManager.GetString("Category_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category page number: {0}..
        /// </summary>
        public static string Category_InvalidPageNumber1 {
            get {
                return ResourceManager.GetString("Category_InvalidPageNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Id mismatch..
        /// </summary>
        public static string Category_Mismatch {
            get {
                return ResourceManager.GetString("Category_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Id mismatch..
        /// </summary>
        public static string Category_Mismatch1 {
            get {
                return ResourceManager.GetString("Category_Mismatch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
        /// </summary>
        public static string Category_NotFoundGetCategoriesWithPies {
            get {
                return ResourceManager.GetString("Category_NotFoundGetCategoriesWithPies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found for GetCategoriesWithPies..
        /// </summary>
        public static string Category_NotFoundGetCategoriesWithPies1 {
            get {
                return ResourceManager.GetString("Category_NotFoundGetCategoriesWithPies1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No category found with id: {0}..
        /// </summary>
        public static string Category_NotFoundId {
            get {
                return ResourceManager.GetString("Category_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No category found with id: {0}..
        /// </summary>
        public static string Category_NotFoundId1 {
            get {
                return ResourceManager.GetString("Category_NotFoundId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories found..
        /// </summary>
        public static string Category_NotFoundList {
            get {
                return ResourceManager.GetString("Category_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories found..
        /// </summary>
        public static string Category_NotFoundList1 {
            get {
                return ResourceManager.GetString("Category_NotFoundList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is null..
        /// </summary>
        public static string Category_Null {
            get {
                return ResourceManager.GetString("Category_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is null..
        /// </summary>
        public static string Category_Null1 {
            get {
                return ResourceManager.GetString("Category_Null1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid coupon id: {0}..
        /// </summary>
        public static string Coupon_InvalidId {
            get {
                return ResourceManager.GetString("Coupon_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid coupon page number: {0}..
        /// </summary>
        public static string Coupon_InvalidPageNumber {
            get {
                return ResourceManager.GetString("Coupon_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Id mismatch..
        /// </summary>
        public static string Coupon_Mismatch {
            get {
                return ResourceManager.GetString("Coupon_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No coupon found with id: {0}..
        /// </summary>
        public static string Coupon_NotFoundId {
            get {
                return ResourceManager.GetString("Coupon_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No coupon found..
        /// </summary>
        public static string Coupon_NotFoundList {
            get {
                return ResourceManager.GetString("Coupon_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon is null..
        /// </summary>
        public static string Coupon_Null {
            get {
                return ResourceManager.GetString("Coupon_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email template id: {0}..
        /// </summary>
        public static string EmailTemplate_InvalidId {
            get {
                return ResourceManager.GetString("EmailTemplate_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email template id: {0}..
        /// </summary>
        public static string EmailTemplate_InvalidId1 {
            get {
                return ResourceManager.GetString("EmailTemplate_InvalidId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email template page number: {0}..
        /// </summary>
        public static string EmailTemplate_InvalidPageNumber {
            get {
                return ResourceManager.GetString("EmailTemplate_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email template page number: {0}..
        /// </summary>
        public static string EmailTemplate_InvalidPageNumber1 {
            get {
                return ResourceManager.GetString("EmailTemplate_InvalidPageNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template Id mismatch..
        /// </summary>
        public static string EmailTemplate_Mismatch {
            get {
                return ResourceManager.GetString("EmailTemplate_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template Id mismatch..
        /// </summary>
        public static string EmailTemplate_Mismatch1 {
            get {
                return ResourceManager.GetString("EmailTemplate_Mismatch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found with id: {0}..
        /// </summary>
        public static string EmailTemplate_NotFoundId {
            get {
                return ResourceManager.GetString("EmailTemplate_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found with id: {0}..
        /// </summary>
        public static string EmailTemplate_NotFoundId1 {
            get {
                return ResourceManager.GetString("EmailTemplate_NotFoundId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found..
        /// </summary>
        public static string EmailTemplate_NotFoundList {
            get {
                return ResourceManager.GetString("EmailTemplate_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found..
        /// </summary>
        public static string EmailTemplate_NotFoundList1 {
            get {
                return ResourceManager.GetString("EmailTemplate_NotFoundList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found with name: {0}..
        /// </summary>
        public static string EmailTemplate_NotFoundName {
            get {
                return ResourceManager.GetString("EmailTemplate_NotFoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email template found with name: {0}..
        /// </summary>
        public static string EmailTemplate_NotFoundName1 {
            get {
                return ResourceManager.GetString("EmailTemplate_NotFoundName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailTemplate is null..
        /// </summary>
        public static string EmailTemplate_Null {
            get {
                return ResourceManager.GetString("EmailTemplate_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailTemplate is null..
        /// </summary>
        public static string EmailTemplate_Null1 {
            get {
                return ResourceManager.GetString("EmailTemplate_Null1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hash provided..
        /// </summary>
        public static string InvalidHash {
            get {
                return ResourceManager.GetString("InvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password information is null..
        /// </summary>
        public static string MobileAuth_ChangePasswordNull {
            get {
                return ResourceManager.GetString("MobileAuth_ChangePasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password information is null..
        /// </summary>
        public static string MobileAuth_ChangePasswordNull1 {
            get {
                return ResourceManager.GetString("MobileAuth_ChangePasswordNull1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration information is null..
        /// </summary>
        public static string MobileAuth_RegisterNull {
            get {
                return ResourceManager.GetString("MobileAuth_RegisterNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration information is null..
        /// </summary>
        public static string MobileAuth_RegisterNull1 {
            get {
                return ResourceManager.GetString("MobileAuth_RegisterNull1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment method found.
        /// </summary>
        public static string Payment_Method_NotFound {
            get {
                return ResourceManager.GetString("Payment_Method_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment option found .
        /// </summary>
        public static string Payment_Options_NotFound {
            get {
                return ResourceManager.GetString("Payment_Options_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pie &apos;{0}&apos; already exists..
        /// </summary>
        public static string Pie_Duplicate {
            get {
                return ResourceManager.GetString("Pie_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pie &apos;{0}&apos; already exists..
        /// </summary>
        public static string Pie_Duplicate1 {
            get {
                return ResourceManager.GetString("Pie_Duplicate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pie category id: {0}..
        /// </summary>
        public static string Pie_InvalidCategoryId {
            get {
                return ResourceManager.GetString("Pie_InvalidCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pie category id: {0}..
        /// </summary>
        public static string Pie_InvalidCategoryId1 {
            get {
                return ResourceManager.GetString("Pie_InvalidCategoryId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pie id: {0}..
        /// </summary>
        public static string Pie_InvalidId {
            get {
                return ResourceManager.GetString("Pie_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pie id: {0}..
        /// </summary>
        public static string Pie_InvalidId1 {
            get {
                return ResourceManager.GetString("Pie_InvalidId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pie page number: {0}..
        /// </summary>
        public static string Pie_InvalidPageNumber {
            get {
                return ResourceManager.GetString("Pie_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pie page number: {0}..
        /// </summary>
        public static string Pie_InvalidPageNumber1 {
            get {
                return ResourceManager.GetString("Pie_InvalidPageNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie Id mismatch..
        /// </summary>
        public static string Pie_Mismatch {
            get {
                return ResourceManager.GetString("Pie_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie Id mismatch..
        /// </summary>
        public static string Pie_Mismatch1 {
            get {
                return ResourceManager.GetString("Pie_Mismatch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pie found with category id: {0}..
        /// </summary>
        public static string Pie_NotFoundCategoryId {
            get {
                return ResourceManager.GetString("Pie_NotFoundCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pie found with category id: {0}..
        /// </summary>
        public static string Pie_NotFoundCategoryId1 {
            get {
                return ResourceManager.GetString("Pie_NotFoundCategoryId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pie found with id: {0}..
        /// </summary>
        public static string Pie_NotFoundId {
            get {
                return ResourceManager.GetString("Pie_NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pie found with id: {0}..
        /// </summary>
        public static string Pie_NotFoundId1 {
            get {
                return ResourceManager.GetString("Pie_NotFoundId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pies found..
        /// </summary>
        public static string Pie_NotFoundList {
            get {
                return ResourceManager.GetString("Pie_NotFoundList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pies found..
        /// </summary>
        public static string Pie_NotFoundList1 {
            get {
                return ResourceManager.GetString("Pie_NotFoundList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie is null..
        /// </summary>
        public static string Pie_Null {
            get {
                return ResourceManager.GetString("Pie_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie is null..
        /// </summary>
        public static string Pie_Null1 {
            get {
                return ResourceManager.GetString("Pie_Null1", resourceCulture);
            }
        }
        /// <summary>
        ///   
        /// </summary>
        public static string Invalid_Filtering
        {
            get
            {
                return ResourceManager.GetString("Invalid_Filtering", resourceCulture);
            }
        }
    }
}
